# Generated by Django 4.2.3 on 2023-12-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Company_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_type", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="image/company"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
