# Generated by Django 4.2.3 on 2023-12-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="Company_code", new_name="company_code",
        ),
    ]
