# Generated by Django 4.2.3 on 2024-01-01 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_hsn", models.PositiveIntegerField(null=True)),
                ("item_unit", models.CharField(max_length=255)),
                ("item_taxable", models.CharField(max_length=255)),
                ("item_gst", models.CharField(max_length=255, null=True)),
                ("item_igst", models.CharField(max_length=255, null=True)),
                ("item_sale_price", models.PositiveIntegerField()),
                ("item_purchase_price", models.PositiveBigIntegerField()),
                ("item_opening_stock", models.PositiveBigIntegerField(default=0)),
                ("item_current_stock", models.PositiveBigIntegerField(default=0)),
                ("item_at_price", models.PositiveBigIntegerField(default=0)),
                ("item_date", models.DateField()),
                ("item_min_stock_maintain", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
