# Generated by Django 4.2.3 on 2023-12-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0002_rename_company_code_company_company_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="position",
            field=models.CharField(
                choices=[("Company", "Company"), ("Employee", "Employee")],
                default="Company",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
