# Generated by Django 4.2.3 on 2023-12-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0003_company_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="position",),
    ]
