# Generated by Django 4.2.3 on 2024-01-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0003_rename_itemmodel_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="item_at_price", new_name="itm_at_price",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_date", new_name="itm_date",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_hsn", new_name="itm_hsn",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_name", new_name="itm_name",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="item_purchase_price",
            new_name="itm_purchase_price",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_sale_price", new_name="itm_sale_price",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="item_current_stock",
            new_name="itm_stock_in_hand",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_taxable", new_name="itm_taxable",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_unit", new_name="itm_unit",
        ),
        migrations.RenameField(
            model_name="item", old_name="item_gst", new_name="itm_vat",
        ),
        migrations.RemoveField(model_name="item", name="item_igst",),
        migrations.RemoveField(model_name="item", name="item_min_stock_maintain",),
        migrations.RemoveField(model_name="item", name="item_opening_stock",),
        migrations.AddField(
            model_name="item",
            name="itm_type",
            field=models.CharField(
                choices=[("Goods", "Goods"), ("Service", "Service")],
                default="Goods",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
