# Generated by Django 4.2.3 on 2024-01-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0004_rename_item_at_price_item_itm_at_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="company_code",),
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billapp.company",
            ),
        ),
    ]
