# Generated by Django 4.2.3 on 2023-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0005_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="image/employee"),
        ),
    ]
