# Generated by Django 4.2.3 on 2023-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0006_employee_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
