# Generated by Django 4.2.3 on 2023-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0007_employee_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_approved",
            field=models.IntegerField(default=0),
        ),
    ]
