# Generated by Django 4.2.3 on 2024-01-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0011_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="user",),
        migrations.AddField(
            model_name="item",
            name="Company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billapp.company",
            ),
        ),
    ]
