# Generated by Django 4.2.3 on 2024-01-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0012_remove_item_user_item_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="Company", new_name="company",
        ),
    ]
