# Generated by Django 4.2.3 on 2024-01-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0013_rename_company_item_company"),
    ]

    operations = [
        migrations.RemoveField(model_name="unitmodel", name="user",),
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unitmodel",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billapp.company",
            ),
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trans_type", models.CharField(max_length=255)),
                (
                    "trans_invoice",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("trans_user_name", models.CharField(max_length=255)),
                ("trans_date", models.DateTimeField()),
                ("trans_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_current_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_adjusted_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_price", models.PositiveBigIntegerField(default=0)),
                ("trans_status", models.CharField(max_length=255)),
                (
                    "trans_created_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billapp.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billapp.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
