# Generated by Django 4.2.3 on 2024-01-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0015_transactions_rename_unitmodel_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="itm_at_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item", name="itm_hsn", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="item", name="itm_purchase_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="item", name="itm_sale_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="itm_stock_in_hand",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="trans_adjusted_qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="trans_current_qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="trans_invoice",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="trans_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="trans_qty",
            field=models.IntegerField(default=0),
        ),
    ]
