# Generated by Django 4.2.3 on 2024-01-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0017_alter_transactions_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billapp.item",
            ),
        ),
    ]
